name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build the card
        run: |
          npm ci
          npm run build

      - name: Upload JS to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/hass-weather-card.js
          asset_name: hass-weather-card.js
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload GZ to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/hass-weather-card.js.gz
          asset_name: hass-weather-card.js.gz
          tag: ${{ github.ref }}
          overwrite: true

      - name: Verify HACS compliance
        uses: hacs/action@main
        with:
          category: plugin
